### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by dkm** [m-labs/dslite2svd#13]
Hi !
I was wondering if a new release is planned ? The last one is ~1 year and some changes already in the main branch are needed by some use cases (like using RTIC with tm4c123). Thanks !

**Comment by sbourdeauducq** [comment]
No; basically we don't plan to invest more in TM4C, and additionally I have become annoyed with platforms like crates.io (as a general concept, not with crates.io in particular). Are you able to use the git version in Cargo.toml?

**Comment by dkm** [comment]
> No; basically we don't plan to invest more in TM4C, 

Are you saying that this repository is going in maintenance mode ? Or even that you don't really plan on doing anything more ? For example I see that `svd2rust` has changed some interfaces recently, so I guess in the near future I will try to update tm4c crates. Should I open a pull-request anyway, or should I try to find another solution ? (maybe this crate could be moved along with `tm4c-hal`?).

> and additionally I have become annoyed with platforms like crates.io (as a general concept, not with crates.io in particular).

I can understand this also...

> Are you able to use the git version in Cargo.toml?

Sure I can, and that's what I'm already doing. I was planning on asking for an update in `tm4c-hal`s after this one, so that everything is up to date. I guess I should ping `tm4c-hal` maintainers to see if they can update their dependencies using git ref instead.

thanks !

**Comment by sbourdeauducq** [comment]
If you open tested and easy-to-accept PRs, I will merge them.

**Comment by dkm** [comment]
Ok, will do that ! Thanks for your time !

**Comment by dkm** [comment]
Hi again,

I was willing to add a git dependency in `tm4c-hal` (see https://github.com/rust-embedded-community/tm4c-hal/pull/43 ) but that's not possible because crates.io does not accept such dependency.
It means that not updating these crates is blocking downstream crates.
If you don't plan on continuing active development of this repository (aside from merging PR), would you be ok with transferring it to `rust-embedded-community` ? Or maybe only part of it (ie. only the generated crates) ?

**Comment by sbourdeauducq** [comment]
@dkm please see private emails.

**Comment by dkm** [comment]
Closing it as it won't happen here.
