### ISSUE TITLE
Updated Crates.io from version 0.9.0 -> 0.9.1 for tm4c123x and tm4c129x crates?

### ISSUE THREAD

**Issue by amcelroy** [m-labs/dslite2svd#18]
Howdy,

Is there a way that I could help update the Crates.io listing for tm4c123x and tm4c129x to support the 0.9.1 versions (commit 77a40f0)? The reason is that I am up-reving the dependencies for the tm4c-hal (https://github.com/rust-embedded-community/tm4c-hal) so that it is compatible with newer RTIC versions. The current fix requires pulling directly from this repo instead of crates.io.

Thanks you for considering

**Comment by sbourdeauducq** [comment]
For political and ideological reasons, crates.io will probably make it difficult for us to update our own project there.
You can easily find a lot of public Rust community drama from recent years - we are not involved in it, but it shows that those are not reasonable people, and I have other things to do than fighting with them.
What's wrong with using the repos? Having more decentralized systems helps against the general class of problems above.

**Comment by amcelroy** [comment]
That all makes sense, I will submit the pull request the tm4c-hal project using this project's git repo instead of crates.io and see what happens. 

Could we tag the latest release as 0.9.1 so that I can have a the correct version selected?

**Comment by sbourdeauducq** [comment]
Done. Last time I checked (been a couple years), crates.io enforced that all dependencies of packages uploaded there are also on crates.io, so I'm not sure how much this will help. I also didn't find a good alternative to cargo when I wanted to move our projects away from it. Good luck :)

**Comment by sbourdeauducq** [comment]
Alternatively we can just reupload to crates.io under a different name. Would probably work fine as interim solution.

**Comment by amcelroy** [comment]
Sorry for the delay, just submitted a PR to [tm4c-hal](https://github.com/rust-embedded-community/tm4c-hal/pull/52) using the tagged v0.9.1 release + a git repo link.

**Comment by eldruin** [comment]
Hi,
Sorry I am not in the loop here, just coming from the https://github.com/rust-embedded-community/tm4c-hal/pull/52 issue.
Indeed changing the dependency to a git link would make the tm4c-hal crate [not publishable](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) anymore.
Could you explain to me why it is a problem to publish a new version of the crates?
A bunch of us (including myself) are tagged as [owners](https://crates.io/crates/tm4c123x) so I do not understand why we would need to talk to anybody at all.
It seems to me like we could do just `cargo publish`.
What am I missing?

**Comment by sbourdeauducq** [comment]
> It seems to me like we could do just `cargo publish`.

OK, do that then.

**Comment by eldruin** [comment]
Alright. [tm4c123x](https://crates.io/crates/tm4c123x/0.9.1) and [tm4c129x](https://crates.io/crates/tm4c129x/0.9.1) 0.9.1 are now published at crates.io.
Thanks everybody! This can be closed now.

**Comment by amcelroy** [comment]
Thank you everyone!
