### ISSUE TITLE
Flash driver for TM4C123

### ISSUE THREAD

**Issue by thejpster** [m-labs/dslite2svd#2]
I couldn't get the flash driver to work for the TM4C123 (actually I'm using an LM4F120) so I resorted to making manual calls to `volatile_store`.

One problem is that the flash write buffer is in fact an array that's 32 words long. The other is that FMC2 needs a write key to be placed in the top 16 bits.

**Comment by whitequark** [comment]
Do you think you could write an "overlay" for it that corrects the deficiencies? In general, in such cases, dslite2svd patches the original svd file when building the SVD definitions. You can see some examples in the [TM4C129 overlay](https://github.com/m-labs/dslite2svd/blob/master/overlay/tm4c129x.patch).

Just add a patch hunk to the `overlay/*.patch` file and run `make`, the build process will ensure that the patch stays up to date even if you add hunks prior to others.

**Comment by thejpster** [comment]
See https://github.com/m-labs/dslite2svd/pull/3.

As a general rule I try and avoid build outputs in my repositories. It was also quite a fiddle trying to get the XML right and generate a patch in the appropriate format. Plus it seems rustfmt and svd2rust have moved on a bit since this was last run, so the changes to lib.rs are huge.

It makes a lib.rs but I haven't been able to test it yet.

**Comment by whitequark** [comment]
Fixed.

**Comment by thejpster** [comment]
Would it be possible to do a cargo publish? Thanks!

**Comment by whitequark** [comment]
Done
