### ISSUE TITLE
Can't build crates generated with latest svd2rust

### ISSUE THREAD

**Issue by thejpster** [m-labs/dslite2svd#4]
If you rebuild with the latest svd2rust, the crates don't compile. I think cortex-m needs upissuing and some of the generated code needs an unsafe block.

**Comment by whitequark** [comment]
This is the reason I keep build products in the repository, actually. Since svd2rust cannot be versioned via Cargo.lock, this is the next best thing.

**Comment by whitequark** [comment]
https://github.com/japaric/svd2rust/pull/173

**Comment by thejpster** [comment]
I guess this is fixed?
